<?php

namespace App\Services;

/**
 * SmartPatchApplier
 *
 * Applies a patch_map (generated by SmartPatchExtractor) to a user's binary file.
 *
 * For each cluster:
 *   1. Find the search pattern in the user's file (ignoring ?? wildcards)
 *   2. If found → write replace bytes (skip ?? positions — leave user bytes intact)
 *   3. If not found → skip cluster + log warning
 */
class SmartPatchApplier
{
    /**
     * Apply a decoded patch_map array to a binary string.
     *
     * @param  string $binary     Raw binary content of the user's ECU file
     * @param  array  $patchMap   Decoded patch_map (from SmartPatchExtractor::extract())
     * @return array [
     *   'content'  => string  patched binary,
     *   'applied'  => int     clusters applied,
     *   'skipped'  => int     clusters skipped,
     *   'warnings' => string[]
     * ]
     * @throws \InvalidArgumentException on file size mismatch
     */
    public function apply(string $binary, array $patchMap): array
    {
        $fileSize     = strlen($binary);
        $expectedSize = $patchMap['file_size'];

        if ($fileSize !== $expectedSize) {
            throw new \InvalidArgumentException(
                "File size mismatch: expected {$expectedSize} bytes, got {$fileSize} bytes."
            );
        }

        $result   = $binary;
        $applied  = 0;
        $skipped  = 0;
        $warnings = [];

        foreach ($patchMap['clusters'] as $index => $cluster) {
            $offsetStart = $cluster['offset_start'];
            $search      = $cluster['search'];
            $replace     = $cluster['replace'];
            $length      = count($search);

            // Boundary check
            if ($offsetStart + $length > $fileSize) {
                $warnings[] = "Cluster #{$index}: offset out of bounds. Skipped.";
                $skipped++;
                continue;
            }

            // Check search pattern against user file (wildcards always match)
            $matches = true;
            for ($i = 0; $i < $length; $i++) {
                if ($search[$i] === '??') {
                    continue; // wildcard — always matches
                }
                $userByte    = strtoupper(bin2hex($result[$offsetStart + $i]));
                $searchByte  = strtoupper($search[$i]);
                if ($userByte !== $searchByte) {
                    $matches = false;
                    break;
                }
            }

            if (!$matches) {
                $warnings[] = "Cluster #{$index} at offset 0x" . dechex($offsetStart) . ": pattern not found. Skipped.";
                $skipped++;
                continue;
            }

            // Apply replace (skip wildcards)
            for ($i = 0; $i < $length; $i++) {
                if ($replace[$i] === '??') {
                    continue; // leave user's byte intact
                }
                $result[$offsetStart + $i] = hex2bin($replace[$i]);
            }

            $applied++;
        }

        return [
            'content'  => $result,
            'applied'  => $applied,
            'skipped'  => $skipped,
            'warnings' => $warnings,
        ];
    }

    /**
     * Convenience: decode JSON patch_map string then apply.
     */
    public function applyFromJson(string $binary, string $patchMapJson): array
    {
        $patchMap = json_decode($patchMapJson, true);

        if (!$patchMap || !isset($patchMap['file_size'], $patchMap['clusters'])) {
            throw new \InvalidArgumentException('Invalid patch_map JSON.');
        }

        return $this->apply($binary, $patchMap);
    }
}
